name: Embedded Builds

on: [push, pull_request]
jobs:
  llvm_clang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
        - TYPE: Release
          NAME: vanilla_llvm12+clang+glibc2.27
          LLVM_VERSION: 12
          STATIC_LINKING: ON
          STATIC_LIBC: OFF
          EMBED_BUILD_LLVM: OFF
          EMBED_USE_LLVM: ON
          RUN_ALL_TESTS: 1
          RUNTIME_TEST_DISABLE: builtin.cgroup,probe.kprobe_offset_fail_size,variable.32-bit tracepoint arg
          TOOLS_TEST_OLDVERSION: biosnoop.bt
          BASE: bionic
          DISTRO: ubuntu-glibc
          VENDOR_GTEST: ON
          BCC_REF: v0.23.0
          ENABLE_SKB_OUTPUT: ON
    steps:
    - uses: actions/checkout@v2
    - name: Build docker container
      run: >
        docker build
        -t bpftrace-embedded-${{ matrix.env['BASE'] }}
        -f docker/Dockerfile.${{ matrix.env['DISTRO'] }}
        --build-arg bcc_ref=${{ matrix.env['BCC_REF'] }}
        --build-arg BASE=${{ matrix.env['BASE'] }}
        --build-arg LLVM_VERSION=${{ matrix.env['LLVM_VERSION'] }}
        --build-arg ALPINE_VERSION=${{ matrix.env['ALPINE_VERSION'] }}
        docker/
    - name: bpftrace embedded build
      env: ${{ matrix.env }}
      run: >
        docker run --privileged
        -v $(pwd):$(pwd)
        -w $(pwd)
        -v /sys/kernel/debug:/sys/kernel/debug:rw
        -v /lib/modules:/lib/modules:ro
        -v /usr/src:/usr/src:ro
        -e LLVM_VERSION=${LLVM_VERSION}
        -e STATIC_LINKING=${STATIC_LINKING}
        -e STATIC_LIBC=${STATIC_LIBC}
        -e EMBED_USE_LLVM=${EMBED_USE_LLVM}
        -e EMBED_BUILD_LLVM=${EMBED_BUILD_LLVM}
        -e RUN_ALL_TESTS=${RUN_ALL_TESTS}
        -e CMAKE_EXTRA_FLAGS="${CMAKE_EXTRA_FLAGS}"
        -e TEST_GROUPS_DISABLE="${TEST_GROUPS_DISABLE}"
        -e RUNTIME_TEST_DISABLE="${RUNTIME_TEST_DISABLE}"
        -e VENDOR_GTEST="${VENDOR_GTEST}"
        -e BUILD_LIBBPF="${BUILD_LIBBPF}"
        -e TOOLS_TEST_OLDVERSION="$TOOLS_TEST_OLDVERSION"
        -e TOOLS_TEST_DISABLE="$TOOLS_TEST_DISABLE"
        -e ENABLE_SKB_OUTPUT="$ENABLE_SKB_OUTPUT"
        bpftrace-embedded-${{ matrix.env['BASE'] }}
        $(pwd)/build-embedded ${TYPE}
        -j`nproc`
    - name: Check linked libs
      env: ${{ matrix.env }}
      run: >
        docker run --privileged
        -v $(pwd):$(pwd)
        -w $(pwd)
        --entrypoint /bin/bash
        bpftrace-embedded-${{ matrix.env['BASE'] }}
        -c "[[ -f $(pwd)/build-embedded/src/bpftrace ]] && ! readelf --dynamic $(pwd)/build-embedded/src/bpftrace | grep NEEDED | grep -v 'libm\|libc\|ld-linux\|libpthread\|libdl\|librt\.so'"
    - name: Strip artifacts
      env: ${{ matrix.env }}
      if: matrix.env['TYPE'] == 'Release'
      run: >
        docker run --privileged
        -v $(pwd):$(pwd)
        -w $(pwd)
        --entrypoint /bin/bash
        bpftrace-embedded-${{ matrix.env['BASE'] }}
        -c "strip --keep-symbol BEGIN_trigger --keep-symbol END_trigger $(pwd)/build-embedded/src/bpftrace"
    - name: Report size
      env: ${{ matrix.env }}
      run: >
        docker run --privileged
        -v $(pwd):$(pwd)
        -w $(pwd)
        --entrypoint /bin/bash
        bpftrace-embedded-${{ matrix.env['BASE'] }}
        -c "echo SIZE: ; du -sh $(pwd)/build-embedded/src/bpftrace"
    - uses: actions/upload-artifact@v1
      with:
        name: bpftrace-${{ matrix.env['TYPE'] }}-${{ matrix.env['NAME'] }}
        path: build-embedded/src/bpftrace
    - uses: actions/upload-artifact@v1
      with:
        name: bpftrace_test-${{ matrix.env['TYPE'] }}-${{ matrix.env['NAME'] }}
        path: build-embedded/tests/bpftrace_test

    - name: Authenticate with docker registry
      if: >
        matrix.env['TYPE'] == 'Release' &&
        (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) &&
        github.repository == 'iovisor/bpftrace'
      env:
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      run: ./docker/scripts/auth.sh ${{ github.repository }}

    - name: Package docker image and push to quay.io
      if: >
        matrix.env['TYPE'] == 'Release' &&
        (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) &&
        github.repository == 'iovisor/bpftrace'
      run: >
        ./docker/scripts/push.sh
        ${{ github.repository }}
        ${{ github.ref }}
        ${{ github.sha }}
        ${{ matrix.env['NAME'] }}
        ${{ matrix.env['EDGE'] }}
